version: 2

jobs:
  build-linux:
    docker:
      - image: sublimetext/unittesting
    steps:
      - checkout
      - run: sh -e /etc/init.d/xvfb start
      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/circleci.sh
      - run: |
          export PATH="$HOME/.local/bin:$PATH"

          # bootstrap the testing environment
          sh circleci.sh bootstrap

          # install Package Control and package denepdencies
          # sh circleci.sh install_package_control

          # run tests with test coverage report
          sh circleci.sh run_tests --coverage

          # testing syntax_test files
          # - sh travis.sh run_syntax_tests
      - run: |
          apt-get install python3-pip -y
          pip3 install codecov
          codecov


  build-macos:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run: curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/circleci.sh
      - run: |
          export PATH="$HOME/.local/bin:$PATH"

          # bootstrap the testing environment
          sh circleci.sh bootstrap

          # install Package Control and package denepdencies
          # sh circleci.sh install_package_control

          # run tests with test coverage report
          sh circleci.sh run_tests --coverage

          # testing syntax_test files
          # - sh travis.sh run_syntax_tests
      - run: |
          brew upgrade python
          pip3 install codecov
          codecov

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-linux
      - build-macos
